export interface GlossaryTerm {
  slug: string;
  term: string;
  shortDefinition: string;
  fullDefinition: string;
  relatedTerms: string[];
  category: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: "eidas-2",
    term: "eIDAS 2.0",
    shortDefinition:
      "The revised EU regulation on electronic identification and trust services, updating the original 2014 eIDAS framework to mandate a European Digital Identity Wallet for all EU citizens.",
    fullDefinition:
      "eIDAS 2.0 (Regulation (EU) 2024/1183) is the comprehensive overhaul of the European Union's framework for electronic identification, authentication, and trust services. Published in the Official Journal of the EU on 30 April 2024 and entering into force on 20 May 2024, it amends the original eIDAS Regulation (EU) No 910/2014. The regulation introduces a paradigm shift in digital identity across Europe by mandating that every EU Member State offer at least one European Digital Identity Wallet (EUDIW) to its citizens and residents. Unlike its predecessor, which relied on voluntary mutual recognition of national eID schemes, eIDAS 2.0 creates an obligation for both public and private sector entities to accept the wallet under defined conditions. The regulation also expands the catalogue of qualified trust services to include electronic attestation of attributes, electronic ledgers, and electronic archiving. It establishes stricter requirements for Qualified Trust Service Providers (QTSPs) and introduces the concept of Person Identification Data (PID) as the foundational identity dataset within the wallet. The Architecture Reference Framework (ARF) provides the technical specifications that guide wallet implementation. Member States have until 2026-2027 to implement the regulation fully, including deploying certified wallets and updating their national eID schemes. eIDAS 2.0 is expected to transform sectors such as banking, healthcare, education, and travel by enabling secure, privacy-preserving, cross-border digital identity verification.",
    relatedTerms: ["eudiw", "qtsp", "arf", "pid"],
    category: "Core Regulation",
  },
  {
    slug: "eudiw",
    term: "European Digital Identity Wallet (EUDIW)",
    shortDefinition:
      "A mobile application that every EU Member State must provide to citizens and residents, enabling them to store and present digital identity credentials and attestations across borders.",
    fullDefinition:
      "The European Digital Identity Wallet (EUDIW) is the centrepiece of eIDAS 2.0. It is a software application, typically running on a mobile device, that allows natural and legal persons in the EU to securely store, manage, and present their Person Identification Data (PID) along with Electronic Attestations of Attributes (EAAs). Each Member State is required to issue at least one wallet to its citizens and residents, free of charge for natural persons. The wallet enables users to authenticate themselves online and offline, sign documents with Qualified Electronic Signatures, and share verified attributes, such as age, professional qualifications, or driving licence data, with relying parties. A key design principle is user control: the holder decides which data to share, with whom, and can leverage privacy-enhancing technologies like selective disclosure to minimise the information revealed. The wallet must meet high Level of Assurance (LoA) requirements and undergo conformity assessment and certification under the Common Criteria or equivalent schemes. It must also support standardised protocols such as OpenID for Verifiable Credentials (OpenID4VC), SD-JWT, and mdoc (ISO 18013-5) as defined in the Architecture Reference Framework. Large-Scale Pilots (LSPs) such as the EU Digital Identity Wallet Consortium (EWC), POTENTIAL, NOBID, and DC4EU are testing real-world use cases ahead of full deployment. Once deployed, very large online platforms, banks performing customer due diligence, and certain public services will be legally required to accept the wallet for identity verification, making the EUDIW a foundational infrastructure for the EU digital single market.",
    relatedTerms: ["eidas-2", "pid", "eaa", "selective-disclosure"],
    category: "Digital Identity",
  },
  {
    slug: "qtsp",
    term: "Qualified Trust Service Provider (QTSP)",
    shortDefinition:
      "An entity granted qualified status by a national supervisory body, authorised to issue qualified certificates, signatures, seals, timestamps, and electronic attestations of attributes under eIDAS.",
    fullDefinition:
      "A Qualified Trust Service Provider (QTSP) is a trust service provider that has been granted qualified status by the supervisory body of an EU Member State after passing a conformity assessment carried out by an accredited conformity assessment body. QTSPs are the highest tier of trust service providers under the eIDAS framework, and their services carry full legal effect across all Member States without the need for additional cross-border agreements. Under eIDAS 2.0, the role of QTSPs expands significantly. In addition to issuing Qualified Electronic Signatures (QES), Qualified Electronic Seals (eSeals), and Qualified Electronic Timestamps, QTSPs can now issue Qualified Electronic Attestations of Attributes (QEAAs). These attestations, covering data such as educational diplomas, professional licences, or company registrations, carry the same legal presumption of accuracy and integrity as the underlying authentic sources from which the data originates. QTSPs are subject to rigorous requirements: they must maintain appropriate security policies, undergo regular audits, notify breaches to the supervisory body, and appear on the national Trusted List. They must also ensure continuity of service and maintain insurance or equivalent financial guarantees. The European Commission maintains an aggregated Trusted List of all QTSPs across Member States, enabling relying parties to verify the qualified status of any provider. For businesses, working with a QTSP is essential for issuing or verifying qualified trust services, and it is a critical compliance step for organisations that need to integrate with the EUDIW ecosystem.",
    relatedTerms: ["qes", "qeaa", "trust-list", "supervisory-body"],
    category: "Trust Services",
  },
  {
    slug: "qes",
    term: "Qualified Electronic Signature (QES)",
    shortDefinition:
      "The highest form of electronic signature under EU law, created using a qualified certificate and a qualified signature creation device, carrying the legal equivalent of a handwritten signature.",
    fullDefinition:
      "A Qualified Electronic Signature (QES) is an advanced electronic signature that is created by a qualified electronic signature creation device and is based on a qualified certificate for electronic signatures issued by a QTSP. Under both eIDAS and eIDAS 2.0, a QES has the legal effect equivalent to a handwritten signature across all EU Member States, without the need for any additional validation or mutual recognition agreement. This makes it the gold standard for electronic signing in the European Union. The qualified certificate binds the signature validation data to the identity of the signatory, who must be a natural person. The qualified signature creation device (QSCD) ensures that the signature creation data is under the sole control of the signatory and that the signature is protected against forgery. Under eIDAS 2.0, the EUDIW must support the creation of QES, enabling any wallet holder to sign documents electronically at the highest level of legal certainty. This is a significant democratisation of qualified signing, as previously QES required separate hardware tokens or smart cards. The regulation mandates that at least one QES service be available to wallet users free of charge for non-professional use. Remote signing solutions, where the QSCD is managed in the cloud by a QTSP on behalf of the signatory, are also gaining prominence and are compatible with the wallet architecture. QES is particularly important in regulated sectors such as legal proceedings, real estate transactions, corporate filings, and cross-border contracts, where the highest level of non-repudiation and legal certainty is required.",
    relatedTerms: ["qtsp", "remote-signing", "eudiw", "wallet-attestation"],
    category: "Trust Services",
  },
  {
    slug: "verifiable-credential",
    term: "Verifiable Credential (VC)",
    shortDefinition:
      "A tamper-evident, cryptographically signed digital credential that can be verified without contacting the issuer, enabling decentralised trust in digital identity systems.",
    fullDefinition:
      "A Verifiable Credential (VC) is a W3C standard data model for expressing credentials in a way that is cryptographically secure, privacy-respecting, and machine-verifiable. In the context of eIDAS 2.0 and the European Digital Identity Wallet, VCs provide the conceptual foundation for how identity data and attributes are represented, issued, held, and presented. A VC contains claims about a subject (such as a person's name, date of birth, or professional qualification), metadata about the credential itself (issuer, issuance date, expiry), and a cryptographic proof, typically a digital signature, that allows any verifier to confirm the credential's authenticity and integrity without needing to contact the issuer directly. This decentralised verification model is essential for the scalability and privacy objectives of the EUDIW. While the eIDAS 2.0 implementing acts specify particular credential formats (notably SD-JWT and mdoc/ISO 18013-5 rather than the W3C VC Data Model directly), the principles of verifiable credentials permeate the entire architecture. Selective disclosure and zero-knowledge proof techniques can be layered on top of VCs to allow holders to reveal only the minimum necessary information. For example, a user could prove they are over 18 without revealing their exact date of birth. The VC ecosystem involves three roles (issuer, holder, and verifier) that map onto the eIDAS concepts of attribute providers, wallet holders, and relying parties. Understanding VCs is fundamental for any organisation planning to issue or consume digital credentials within the European digital identity ecosystem.",
    relatedTerms: ["did", "selective-disclosure", "sd-jwt", "openid4vc"],
    category: "Technical Standards",
  },
  {
    slug: "did",
    term: "Decentralized Identifier (DID)",
    shortDefinition:
      "A globally unique identifier that can be resolved to a DID document containing public keys and service endpoints, enabling verifiable, self-sovereign digital identity without a central registry.",
    fullDefinition:
      "A Decentralized Identifier (DID) is a W3C standard for a new type of globally unique identifier designed to enable individuals, organisations, and devices to create and control their own digital identities without reliance on a centralised authority. A DID is a URI that resolves to a DID document, which contains public keys, authentication methods, and service endpoints that allow the DID subject to prove control over the identifier and establish secure communication channels. DIDs can be anchored on various underlying systems, including blockchains, distributed ledgers, peer-to-peer networks, or even static web resources, depending on the DID method used. In the eIDAS 2.0 context, the role of DIDs is nuanced. The Architecture Reference Framework does not mandate DIDs as a core component of the EUDIW infrastructure; instead, it focuses on credential formats like SD-JWT and mdoc. However, DIDs remain relevant in the broader Self-Sovereign Identity (SSI) ecosystem and may be used by certain trust service providers, attribute providers, or wallet implementations for cryptographic key management and entity identification. Some Large-Scale Pilots explore DID-based approaches for specific use cases. The relationship between DIDs and eIDAS is an evolving area: while the regulation is technology-neutral in principle, the implementing acts and ARF have so far favoured more conventional PKI-based trust models. Organisations building on or integrating with the EUDIW should understand DIDs as part of the wider verifiable credential landscape, even if direct DID usage in the core wallet protocol is limited.",
    relatedTerms: ["ssi", "verifiable-credential", "arf", "trust-framework"],
    category: "Technical Standards",
  },
  {
    slug: "relying-party",
    term: "Relying Party",
    shortDefinition:
      "An entity, public or private, that relies on the EUDIW or electronic identification means to verify the identity or attributes of a user for the purpose of providing a service.",
    fullDefinition:
      "A Relying Party in the eIDAS 2.0 framework is any natural or legal person that depends on electronic identification, authentication, or electronic attestations of attributes presented via the European Digital Identity Wallet or other recognised eID means to deliver a service or fulfil a legal obligation. Under the revised regulation, the concept of relying parties is significantly expanded and formalised compared to the original eIDAS. Certain categories of relying parties are now legally required to accept the EUDIW when users choose to present it. These mandatory acceptance scenarios include: very large online platforms (as defined under the Digital Services Act) for user authentication; financial institutions performing customer identification under anti-money laundering rules; healthcare providers when required by EU or national law to verify patient identity; and public administrations for access to digital public services. Relying parties must register with the Member State in which they are established before accessing wallet data, and they must declare in advance which attributes they intend to request and for what purpose. This registration requirement is a key privacy safeguard: it prevents unauthorised data harvesting and gives supervisory bodies oversight of who is accessing citizen data. Relying parties must also comply with data minimisation principles, requesting only the attributes strictly necessary for the service. The wallet interface will clearly present to the user what data is being requested and by whom, empowering informed consent. For businesses, understanding the relying party framework is essential: organisations must assess whether they fall into a mandatory acceptance category, implement the technical integration to verify wallet presentations, and comply with registration and data protection requirements.",
    relatedTerms: ["eudiw", "eidas-2", "pid", "selective-disclosure"],
    category: "Core Regulation",
  },
  {
    slug: "eid",
    term: "Electronic Identification (eID)",
    shortDefinition:
      "The process of using electronic means to verify a person's identity, forming the foundation of the eIDAS regulation and the basis for cross-border digital identity in the EU.",
    fullDefinition:
      "Electronic Identification (eID) refers to the use of digital credentials and electronic processes to establish and verify the identity of a natural or legal person. Under the original eIDAS regulation, eID was built around national electronic identification schemes that Member States could voluntarily notify to the European Commission, enabling cross-border mutual recognition. However, uptake was limited: only a fraction of Member States notified their schemes, and cross-border usage remained low. eIDAS 2.0 fundamentally changes this landscape. While the notification mechanism for national eID schemes is retained, it is now complemented, and in practice overshadowed, by the mandatory provision of the European Digital Identity Wallet. The regulation requires that every Member State offer at least one EUDIW, which itself functions as an eID means at a high Level of Assurance. The wallet approach addresses many of the shortcomings of the original eID framework: it provides a common user experience across Member States, supports both online and offline use cases, and integrates identity verification with attribute attestation and electronic signing. eID within the wallet is based on Person Identification Data (PID), which includes a minimum mandatory dataset, typically name, date of birth, and a unique identifier, issued by or on behalf of the Member State. The PID is the anchor of trust in the wallet ecosystem, as it binds the wallet holder to a verified identity. For organisations, understanding eID in the context of eIDAS 2.0 means recognising that the wallet is the primary channel through which European citizens will prove their identity digitally, and that relying parties must be prepared to accept it.",
    relatedTerms: ["eid-scheme", "loa", "pid", "eudiw"],
    category: "Digital Identity",
  },
  {
    slug: "trust-framework",
    term: "Trust Framework",
    shortDefinition:
      "A set of rules, policies, and technical standards that govern how digital identities and credentials are issued, managed, and verified within a defined ecosystem.",
    fullDefinition:
      "A Trust Framework is a structured set of agreements, rules, policies, technical specifications, and governance mechanisms that define how trust is established, maintained, and verified among participants in a digital identity ecosystem. In the eIDAS 2.0 context, the trust framework encompasses the regulation itself, its implementing acts, the Architecture Reference Framework (ARF), the Trusted Lists, and the conformity assessment and supervisory structures. Together, these elements create a comprehensive governance layer that enables relying parties, issuers, wallet providers, and end users to interact with confidence. The eIDAS trust framework is unique in its regulatory backing: unlike many industry-led trust frameworks that rely on voluntary participation, eIDAS 2.0 creates legally binding obligations. Qualified trust services carry automatic cross-border legal effect, and the Trusted Lists provide a machine-readable registry of qualified providers across all Member States. The trust framework also defines the roles and responsibilities of each actor: Member States must issue wallets and PID; Qualified Trust Service Providers issue qualified attestations; attribute providers supply authoritative data; relying parties consume credentials under strict data minimisation rules; and supervisory bodies oversee compliance. For organisations, engaging with the eIDAS trust framework means understanding not just the technical integration requirements (credential formats, protocols, security standards) but also the governance obligations: registration as a relying party, compliance with data protection rules, and adherence to the principle of purpose limitation. The trust framework is what transforms a set of technical standards into a functioning, legally recognised ecosystem for digital identity.",
    relatedTerms: ["eidas-2", "arf", "trust-list", "supervisory-body"],
    category: "Governance",
  },
  {
    slug: "pid",
    term: "Person Identification Data (PID)",
    shortDefinition:
      "The core set of identity attributes, such as name, date of birth, and a unique identifier, issued by a Member State and stored in the EUDIW, forming the foundation of the wallet holder's digital identity.",
    fullDefinition:
      "Person Identification Data (PID) is the foundational identity dataset within the European Digital Identity Wallet. It represents the minimum set of attributes necessary to uniquely identify a natural person, issued by or on behalf of a Member State. The PID typically includes the holder's family name, given name, date of birth, and a unique persistent identifier assigned by the issuing Member State. Additional attributes such as nationality, place of birth, or address may also be included depending on national implementation. The PID is the trust anchor of the wallet ecosystem: it is the only credential in the wallet that is directly issued by a governmental authority (or its delegate), and it serves as the basis for linking other Electronic Attestations of Attributes to a verified identity. When a relying party requests identity verification via the wallet, the PID is the primary credential presented. The issuance of PID must meet the high Level of Assurance as defined in the implementing acts, meaning that the identity proofing process, whether in person or remote, must provide a high degree of confidence that the claimed identity is genuine. The PID is issued in standardised credential formats (SD-JWT and mdoc) as specified by the Architecture Reference Framework, ensuring interoperability across all EU wallets. For organisations integrating with the EUDIW, the PID is the most common credential they will encounter. Understanding its structure, the trust model behind it, and the verification process is essential for implementing compliant and secure relying party services.",
    relatedTerms: ["eudiw", "eidas-2", "loa", "eid"],
    category: "Digital Identity",
  },
  {
    slug: "eaa",
    term: "Electronic Attestation of Attributes (EAA)",
    shortDefinition:
      "A digitally signed attestation that confirms specific attributes of a person, such as age, qualifications, or address, issued by an attribute provider and stored in the EUDIW.",
    fullDefinition:
      "An Electronic Attestation of Attributes (EAA) is a credential issued by an attribute provider that attests to specific characteristics, qualities, rights, or permissions of a natural or legal person. Under eIDAS 2.0, EAAs are a new category of trust service that extends the wallet beyond basic identity verification into a rich ecosystem of verifiable claims. EAAs can cover a wide range of attributes: educational qualifications (university degrees, professional certifications), health data (vaccination records, prescriptions), financial information (bank account ownership, credit scores), corporate attributes (power of representation, company registration), and everyday credentials (age verification, address confirmation, driving licence data). An EAA is issued by an attribute provider, which could be a public authority, a private entity, or a Qualified Trust Service Provider, and is cryptographically signed to ensure authenticity and integrity. When stored in the EUDIW, the holder can selectively present specific attributes from the EAA to relying parties as needed. The key distinction in eIDAS 2.0 is between non-qualified EAAs and Qualified Electronic Attestations of Attributes (QEAAs). Non-qualified EAAs may be issued by any entity and carry no automatic legal presumption; their trustworthiness depends on bilateral agreements or sectoral rules. QEAAs, by contrast, are issued by QTSPs and benefit from a legal presumption of accuracy, meeting specific regulatory requirements. For businesses, EAAs represent a major opportunity: organisations can both issue EAAs (as attribute providers) and consume them (as relying parties), enabling streamlined verification processes that reduce friction and improve user experience while maintaining regulatory compliance.",
    relatedTerms: ["qeaa", "eudiw", "attribute-provider", "selective-disclosure"],
    category: "Digital Identity",
  },
  {
    slug: "qeaa",
    term: "Qualified Electronic Attestation of Attributes (QEAA)",
    shortDefinition:
      "An electronic attestation of attributes issued by a QTSP, carrying a legal presumption of accuracy and cross-border validity equivalent to a legally issued attestation in paper form.",
    fullDefinition:
      "A Qualified Electronic Attestation of Attributes (QEAA) is the highest tier of attribute attestation under eIDAS 2.0. Issued exclusively by Qualified Trust Service Providers (QTSPs), a QEAA benefits from a legal presumption that the attributes it contains are accurate and that the attestation has been issued in compliance with the regulation. This legal presumption holds across all EU Member States without the need for additional recognition or validation. QEAAs are particularly significant in scenarios where attribute verification has legal consequences. For example, proving professional qualifications (a doctor's licence to practise), confirming power of representation for a company, or verifying educational credentials for regulated professions. The QTSP issuing a QEAA must verify the attributes against authentic sources (such as government registries, educational institutions, or professional bodies) and must comply with all the requirements for qualified trust services, including security, auditing, and supervision. Under eIDAS 2.0, Member States must ensure that attributes attested by public sector bodies are available for issuance as QEAAs, either directly by the public body acting as or through a QTSP, or via designated attribute providers. This creates a pathway for the digitisation of government-issued documents and certificates. For relying parties, receiving a QEAA provides the highest level of legal certainty about the accuracy of the attested attributes. For businesses that need to verify credentials as part of regulatory compliance, such as banks verifying customer identity or employers verifying professional licences, QEAAs offer a streamlined, legally robust mechanism that replaces manual document verification.",
    relatedTerms: ["eaa", "qtsp", "attribute-provider", "trust-list"],
    category: "Trust Services",
  },
  {
    slug: "arf",
    term: "Architecture Reference Framework (ARF)",
    shortDefinition:
      "The technical specification document that defines the architecture, protocols, credential formats, and security requirements for the European Digital Identity Wallet ecosystem.",
    fullDefinition:
      "The Architecture Reference Framework (ARF) is the master technical specification developed by the European Commission, in collaboration with Member States and technical experts, to guide the implementation of the European Digital Identity Wallet. Published and regularly updated as part of the eIDAS 2.0 toolbox process, the ARF defines the overall system architecture, component interactions, credential formats, communication protocols, security requirements, and trust model for the EUDIW ecosystem. The ARF specifies that the wallet must support at least two credential formats: SD-JWT (Selective Disclosure JSON Web Token) for representing credentials as signed JSON structures with built-in selective disclosure, and mdoc (ISO 18013-5) originally developed for mobile driving licences but adapted as a general-purpose credential format. For presentation protocols, the ARF mandates support for OpenID for Verifiable Credentials (OpenID4VC), including OpenID4VP (Verifiable Presentations) for presenting credentials and OpenID4VCI (Verifiable Credential Issuance) for receiving them. The ARF also addresses wallet attestation mechanisms, specifically how a relying party can verify that a wallet application is genuine and certified, and key management requirements, including the use of secure elements or trusted execution environments on the user's device. Security and privacy are core concerns: the ARF includes requirements for preventing relying party tracking, ensuring unlinkability of transactions where appropriate, and supporting pseudonymous authentication. For organisations building wallet solutions, developing relying party integrations, or issuing credentials, the ARF is the essential technical reference. It is a living document, updated through successive versions to reflect feedback from Large-Scale Pilots and ongoing standardisation work in bodies like ETSI, CEN, and ISO.",
    relatedTerms: ["eudiw", "sd-jwt", "mdoc", "openid4vc"],
    category: "Technical Standards",
  },
  {
    slug: "lsp",
    term: "Large-Scale Pilot (LSP)",
    shortDefinition:
      "EU-funded multi-country projects that test the European Digital Identity Wallet in real-world scenarios across various sectors before its full deployment.",
    fullDefinition:
      "Large-Scale Pilots (LSPs) are EU-funded projects designed to test the European Digital Identity Wallet in realistic, cross-border scenarios ahead of full regulatory deployment. Under eIDAS 2.0, the European Commission launched four major LSPs in 2023, each involving consortia of Member States, public authorities, private companies, and technology providers. The four pilots are: the EU Digital Identity Wallet Consortium (EWC), focusing on travel and organisational identity; POTENTIAL, covering areas such as eGovernment services, opening bank accounts, SIM registration, and digital signing; NOBID, centred on payment and financial services use cases; and DC4EU, addressing education credentials and social security. These pilots serve multiple purposes. First, they validate the technical specifications of the Architecture Reference Framework by implementing wallet prototypes and testing interoperability across different national implementations. Second, they explore user experience and usability, gathering feedback from real users interacting with wallet-based services. Third, they identify legal, regulatory, and organisational barriers that need to be addressed before full deployment. Fourth, they help build the ecosystem by engaging relying parties, attribute providers, and trust service providers in practical integration exercises. The results of the LSPs directly feed back into the refinement of the ARF, implementing acts, and certification requirements. For organisations considering early adoption, participation in or engagement with an LSP provides invaluable practical experience, access to emerging standards, and the opportunity to shape the ecosystem before mandatory requirements take effect. The LSPs are expected to run through 2025, with their findings informing the final implementation timeline.",
    relatedTerms: ["eudiw", "arf", "eidas-2", "relying-party"],
    category: "Governance",
  },
  {
    slug: "eseal",
    term: "Electronic Seal (eSeal)",
    shortDefinition:
      "An electronic equivalent of a business stamp, used by legal persons to guarantee the origin and integrity of documents and data, with qualified eSeals carrying full cross-border legal effect.",
    fullDefinition:
      "An Electronic Seal (eSeal) is the digital equivalent of a traditional company stamp or seal, used by legal persons (organisations, companies, public bodies) to guarantee the origin and integrity of data and documents. Under eIDAS, while electronic signatures are linked to natural persons, eSeals are linked to legal persons, making them the appropriate instrument when an organisation, rather than a specific individual, needs to vouch for a document. eIDAS 2.0 retains and strengthens the eSeal framework from the original regulation. Qualified Electronic Seals (QeSeals), created using a qualified certificate and a qualified seal creation device issued by a QTSP, enjoy the legal presumption of integrity of the data and of the correctness of the origin of the data to which the seal is linked. This presumption holds across all EU Member States. eSeals are widely used in automated processes: invoicing systems, official government communications, certificate issuance, and batch document processing. Because they are applied by systems rather than individuals, they are ideal for high-volume, machine-driven workflows. Under eIDAS 2.0, the EUDIW ecosystem will also support eSeals for organisational identity. An organisation's wallet instance may carry attestations sealed by the organisation, and relying parties will be able to verify these seals to confirm the origin of organisational credentials. For businesses, eSeals offer a way to authenticate large volumes of documents efficiently while maintaining legal validity. They are particularly relevant for invoices, contracts, official communications, audit logs, and any automated document workflow where the organisation's identity and document integrity must be verifiable.",
    relatedTerms: ["qtsp", "qes", "trust-list", "conformity-assessment"],
    category: "Trust Services",
  },
  {
    slug: "etimestamp",
    term: "Electronic Timestamp",
    shortDefinition:
      "An electronic attestation that binds data to a particular point in time, providing evidence that the data existed in a certain form at that moment.",
    fullDefinition:
      "An Electronic Timestamp is a trust service that binds a set of data to a particular point in time, providing cryptographic evidence that the data existed and was in a specific form at that moment. Under eIDAS, timestamps are used to prove the existence and integrity of documents, transactions, and other digital data at a given time, a capability that is essential in legal, financial, and regulatory contexts. Qualified Electronic Timestamps, issued by Qualified Trust Service Providers, enjoy a legal presumption of accuracy of the date and time they indicate and of the integrity of the data to which the date and time are bound. This legal presumption is valid across all EU Member States. eIDAS 2.0 retains the qualified timestamp as a core trust service. Timestamps are commonly combined with electronic signatures and seals: a signed document is timestamped to prove not only who signed it but when it was signed. This is critical for long-term validation, where a signature must remain verifiable even after the signing certificate has expired. The timestamp proves the signature was valid at the time it was applied. In the context of the EUDIW, timestamps may be used in wallet transaction logs, credential issuance records, and audit trails. They also play a role in regulatory compliance scenarios such as financial trade recording, intellectual property filings, and contract execution timelines. For businesses, integrating qualified timestamps into document workflows is a straightforward way to enhance legal certainty and regulatory compliance, particularly when dealing with cross-border transactions or disputes where the timing of events is material.",
    relatedTerms: ["qtsp", "qes", "eseal", "trust-list"],
    category: "Trust Services",
  },
  {
    slug: "edelivery",
    term: "Electronic Delivery (eDelivery)",
    shortDefinition:
      "A qualified trust service for transmitting electronic data that provides evidence of sending and receipt, with legal effect equivalent to registered postal mail.",
    fullDefinition:
      "Electronic Delivery (eDelivery), formally known as Electronic Registered Delivery Service, is a trust service that enables the secure transmission of electronic data between parties, providing evidence relating to the handling of the transmitted data, including proof of sending and receiving, and protecting against the risk of loss, theft, damage, or alteration. Under eIDAS, a Qualified Electronic Registered Delivery Service (QERDS) benefits from a legal presumption regarding the integrity of the data, the sending and receipt of the data by the identified sender and recipient, and the accuracy of the date and time of sending and receipt. This gives electronic delivery legal effects comparable to traditional registered postal mail. eIDAS 2.0 retains and reinforces this trust service. In an increasingly digital regulatory environment, eDelivery is essential for formal communications that require legal proof of transmission: court filings, regulatory notifications, official correspondence between businesses and government, contract deliveries, and shareholder communications. The service typically involves the identification of the sender and recipient (often using eID or qualified certificates), encryption of the data in transit, and the generation of qualified timestamps and receipts. For the EUDIW ecosystem, eDelivery may serve as a complementary channel for transmitting credentials, notifications, and official communications between wallet holders, relying parties, and attribute providers. For businesses, implementing eDelivery, particularly in its qualified form, reduces legal risk in formal communications, eliminates disputes about whether and when documents were sent or received, and supports compliance with regulatory requirements that mandate provable delivery of information.",
    relatedTerms: ["qtsp", "etimestamp", "eidas-2", "trust-list"],
    category: "Trust Services",
  },
  {
    slug: "ssi",
    term: "Self-Sovereign Identity (SSI)",
    shortDefinition:
      "A model for digital identity in which individuals fully control their own identity data without depending on a central authority, often leveraging decentralised technologies.",
    fullDefinition:
      "Self-Sovereign Identity (SSI) is a model and movement in digital identity that places the individual at the centre of identity management. Under SSI principles, individuals create, own, and control their identity credentials without depending on any single centralised authority or intermediary. The core tenets of SSI include user control and consent, minimal disclosure, portability, and interoperability. Technically, SSI ecosystems typically rely on Decentralized Identifiers (DIDs), Verifiable Credentials (VCs), and distributed ledger or peer-to-peer technologies to enable trust without centralised identity providers. The relationship between SSI and eIDAS 2.0 is complex and often debated. On one hand, the EUDIW embodies several SSI principles: it gives holders control over their data, supports selective disclosure, and enables privacy-preserving interactions with relying parties. The wallet architecture follows the issuer-holder-verifier triangle that is central to SSI. On the other hand, the eIDAS 2.0 framework is fundamentally anchored in government-issued identity (PID) and a regulated trust model (QTSPs, Trusted Lists, supervisory bodies), which departs from the fully decentralised, authority-independent vision of pure SSI. The ARF has also chosen specific credential formats (SD-JWT, mdoc) and protocols (OpenID4VC) over more SSI-native technologies (like DIDComm or W3C VC Data Model with JSON-LD). Some in the SSI community view eIDAS 2.0 as a pragmatic implementation of SSI principles within a regulatory context, while others see it as a parallel but distinct approach. For organisations, understanding SSI provides valuable context for the design philosophy behind the EUDIW, even if the specific technology choices differ from a pure SSI stack.",
    relatedTerms: ["did", "verifiable-credential", "eudiw", "selective-disclosure"],
    category: "Digital Identity",
  },
  {
    slug: "loa",
    term: "Level of Assurance (LoA)",
    shortDefinition:
      "A measure of confidence in the identity verification process, classified as low, substantial, or high under eIDAS, determining the trust level of an electronic identification means.",
    fullDefinition:
      "Level of Assurance (LoA) is a classification that indicates the degree of confidence in the identity proofing, authentication, and management processes behind an electronic identification means. Under the eIDAS framework, three levels are defined: low, substantial, and high. A low LoA provides a limited degree of confidence in the claimed identity; substantial provides a higher degree of confidence, typically involving multi-factor authentication and verified identity proofing; and high provides the highest degree of confidence, requiring in-person or equivalent remote identity proofing and strong authentication mechanisms resistant to sophisticated attacks. Under eIDAS 2.0, the European Digital Identity Wallet must operate at the high Level of Assurance for its Person Identification Data. This means the identity proofing process used to issue PID to a wallet holder must meet the stringent requirements of LoA high, as specified in Commission Implementing Regulation (EU) 2015/1502 and any updated implementing acts under eIDAS 2.0. The high LoA requirement reflects the critical role the wallet plays as a government-backed identity instrument with cross-border legal effect. For relying parties, the LoA determines the level of trust they can place in an identity assertion. Relying parties offering services that require strong identity verification, such as opening bank accounts, accessing health records, or signing legal documents, will typically require LoA high. The LoA concept helps organisations calibrate their identity requirements to the risk level of the service they provide, ensuring that the verification process is proportionate to the potential harm of identity fraud.",
    relatedTerms: ["eid", "pid", "eid-scheme", "eudiw"],
    category: "Core Regulation",
  },
  {
    slug: "zero-knowledge-proof",
    term: "Zero-Knowledge Proof (ZKP)",
    shortDefinition:
      "A cryptographic method that allows one party to prove a statement is true without revealing any underlying data, enabling privacy-preserving identity verification.",
    fullDefinition:
      "A Zero-Knowledge Proof (ZKP) is a cryptographic technique that enables one party (the prover) to demonstrate to another party (the verifier) that a specific statement is true without revealing any information beyond the truth of the statement itself. In the context of digital identity and eIDAS 2.0, ZKPs represent a powerful tool for privacy preservation. For example, a wallet holder could prove they are over 18 years old without revealing their actual date of birth, or prove they hold a valid professional licence without disclosing the licence number or issuing authority. The eIDAS 2.0 regulation emphasises user privacy and data minimisation, and the Architecture Reference Framework acknowledges the importance of privacy-enhancing technologies. While the initial ARF specifications focus on selective disclosure mechanisms within SD-JWT and mdoc formats, which provide a practical level of privacy by allowing holders to reveal only chosen attributes, zero-knowledge proofs offer a more advanced layer of privacy by enabling predicate proofs (proving a value meets a condition without revealing the value) and unlinkability (preventing verifiers from correlating transactions). The implementation of ZKPs in the EUDIW context is an area of active research and standardisation. Some credential formats, such as those based on BBS+ signatures or Camenisch-Lysyanskaya signatures, natively support ZKP-based selective disclosure. Whether and how ZKPs will be incorporated into the EUDIW remains a topic of ongoing discussion. For organisations interested in privacy-first identity verification, understanding ZKPs provides insight into the future direction of the European digital identity ecosystem and the technical possibilities for going beyond basic selective disclosure.",
    relatedTerms: ["selective-disclosure", "verifiable-credential", "eudiw", "sd-jwt"],
    category: "Technical Standards",
  },
  {
    slug: "selective-disclosure",
    term: "Selective Disclosure",
    shortDefinition:
      "A privacy-enhancing capability that allows a credential holder to present only specific attributes from a credential rather than the entire dataset.",
    fullDefinition:
      "Selective Disclosure is a privacy-enhancing feature of digital credential systems that enables a holder to reveal only specific attributes from a credential when presenting it to a verifier, rather than sharing the entire credential content. This principle is fundamental to the design of the European Digital Identity Wallet under eIDAS 2.0, reflecting the regulation's strong emphasis on data minimisation and user control. For example, if a wallet holds a driving licence credential containing the holder's name, date of birth, address, licence categories, and photo, selective disclosure allows the holder to present only the licence categories to a car rental company, without revealing their home address or exact date of birth. The ARF specifies two credential formats that support selective disclosure natively: SD-JWT (Selective Disclosure JSON Web Token), which uses salted hashes to allow individual claims to be revealed or withheld; and mdoc (ISO 18013-5), which structures credentials into distinct data elements that can be independently released. Both formats ensure that the verifier can still cryptographically verify the authenticity and integrity of the disclosed attributes, even when other attributes are withheld. Selective disclosure goes hand in hand with the eIDAS 2.0 requirement that relying parties must request only the attributes that are strictly necessary for the service they provide. The wallet interface will present the user with a clear view of what data is being requested, and the user can approve or decline. For organisations, supporting selective disclosure is not optional; it is a core architectural requirement. Relying parties must design their attribute requests to be minimal, and their systems must be capable of verifying partially disclosed credentials.",
    relatedTerms: ["sd-jwt", "mdoc", "eudiw", "zero-knowledge-proof"],
    category: "Digital Identity",
  },
  {
    slug: "mdl",
    term: "Mobile Driving Licence (mDL)",
    shortDefinition:
      "A digital version of a physical driving licence stored on a mobile device, standardised under ISO 18013-5, and one of the flagship use cases for the European Digital Identity Wallet.",
    fullDefinition:
      "A Mobile Driving Licence (mDL) is a digital representation of a traditional physical driving licence, stored on a mobile device and presented electronically for verification. Standardised under ISO 18013-5, the mDL was one of the earliest and most prominent use cases for verifiable mobile credentials and has directly influenced the design of the European Digital Identity Wallet. The mDL standard defines the data model, security mechanisms, and presentation protocols for a driving licence credential on a mobile device. It supports both online (remote) and offline (proximity-based, using NFC or Bluetooth) verification scenarios, and includes built-in selective disclosure, allowing the holder to present only the relevant data elements (e.g., proving they hold a category B licence without revealing their address). Under eIDAS 2.0, the mDL is one of the key credentials expected to be available in the EUDIW. Several Large-Scale Pilots are testing mDL issuance and verification as part of their wallet implementations. The mdoc credential format used in the EUDIW architecture is directly derived from the ISO 18013-5 standard, making the mDL a natural fit. For users, an mDL in their wallet means they can prove their driving qualifications digitally, at traffic stops, car rental desks, or insurance applications, without carrying a physical card. For businesses in the automotive, insurance, and mobility sectors, the mDL represents a significant opportunity to streamline customer onboarding and compliance checks. Understanding the mDL is also technically important because the mdoc format it pioneered is now a general-purpose credential format in the EUDIW ecosystem, used for many types of credentials beyond driving licences.",
    relatedTerms: ["mdoc", "eudiw", "selective-disclosure", "arf"],
    category: "Digital Identity",
  },
  {
    slug: "openid4vc",
    term: "OpenID for Verifiable Credentials (OpenID4VC)",
    shortDefinition:
      "A family of protocols built on OpenID Connect that standardise the issuance, presentation, and verification of digital credentials, adopted as the core protocol suite for the EUDIW.",
    fullDefinition:
      "OpenID for Verifiable Credentials (OpenID4VC) is a suite of protocols developed by the OpenID Foundation that extends the widely deployed OpenID Connect framework to support the issuance, presentation, and verification of digital credentials. The suite includes several key specifications: OpenID4VCI (Verifiable Credential Issuance), which defines how a wallet obtains credentials from an issuer; OpenID4VP (Verifiable Presentations), which defines how a wallet presents credentials to a verifier; and SIOPv2 (Self-Issued OpenID Provider v2), which enables the wallet itself to act as an identity provider. The Architecture Reference Framework for the European Digital Identity Wallet has adopted OpenID4VC as the primary protocol family for credential issuance and presentation. This choice reflects a pragmatic approach: OpenID Connect is already widely adopted in the industry, and building on it lowers the barrier to adoption for relying parties and issuers who already have OIDC infrastructure. The protocols are designed to be credential-format-agnostic, supporting both SD-JWT and mdoc formats as required by the ARF. OpenID4VC supports both same-device and cross-device flows (e.g., scanning a QR code on a laptop with a phone wallet), online and offline scenarios, and various trust establishment mechanisms. For organisations preparing to integrate with the EUDIW, understanding OpenID4VC is essential. Relying parties will use OpenID4VP to request and verify credential presentations from wallets, while credential issuers will use OpenID4VCI to deliver credentials to wallet holders. The protocols include security features such as request signing, response encryption, and nonce-based replay protection that implementers must correctly handle.",
    relatedTerms: ["arf", "sd-jwt", "mdoc", "eudiw"],
    category: "Technical Standards",
  },
  {
    slug: "sd-jwt",
    term: "SD-JWT (Selective Disclosure JSON Web Token)",
    shortDefinition:
      "A credential format that extends standard JWTs with selective disclosure capabilities, allowing holders to reveal only chosen claims, adopted as a core format for the EUDIW.",
    fullDefinition:
      "SD-JWT (Selective Disclosure JSON Web Token) is a credential format specified by the IETF that extends the widely used JSON Web Token (JWT) standard with built-in selective disclosure capabilities. In a standard JWT, all claims are visible to any party that receives the token. SD-JWT addresses this by hashing individual claims with unique salts during issuance; the holder then selectively reveals specific claims by providing the corresponding salt values, while other claims remain hidden as opaque hash values. This enables privacy-preserving credential presentations without requiring advanced cryptographic techniques like zero-knowledge proofs. The Architecture Reference Framework for the EUDIW has adopted SD-JWT as one of the two mandatory credential formats (alongside mdoc). SD-JWT is particularly well suited for web-based and API-driven interactions, as it builds on the JSON and JOSE standards that are already ubiquitous in web development. The format supports key binding, which ties the credential to a specific holder key, preventing credential transfer or theft. SD-JWT also supports batch issuance and can carry complex claim structures including nested objects and arrays. For developers and organisations building EUDIW integrations, SD-JWT is a practical and accessible format. Its foundation on established web standards means that existing JWT libraries and infrastructure can be extended to support it, reducing implementation effort. When combined with OpenID4VC protocols, SD-JWT provides a complete stack for credential issuance and selective presentation. Organisations that already use JWTs for API authentication or identity federation will find SD-JWT a natural extension of their existing technology stack, making it an attractive option for early adoption of EUDIW-compatible credential handling.",
    relatedTerms: ["selective-disclosure", "openid4vc", "arf", "mdoc"],
    category: "Technical Standards",
  },
  {
    slug: "mdoc",
    term: "mdoc (ISO 18013-5)",
    shortDefinition:
      "A CBOR-based credential format originally developed for mobile driving licences and adopted as a core credential format for the EUDIW, supporting offline verification and selective disclosure.",
    fullDefinition:
      "mdoc is a credential format defined in the ISO 18013-5 standard, originally developed for mobile driving licences (mDL) and subsequently adopted as one of the two mandatory credential formats for the European Digital Identity Wallet alongside SD-JWT. Unlike SD-JWT, which is based on JSON and the JOSE standard family, mdoc uses CBOR (Concise Binary Object Representation) for data encoding and COSE (CBOR Object Signing and Encryption) for cryptographic operations. This makes mdoc particularly efficient in terms of data size, an important consideration for offline and proximity-based scenarios where data is exchanged via NFC or Bluetooth. mdoc structures credentials into namespaces and data elements, each of which can be independently disclosed, providing built-in selective disclosure at the attribute level. The format supports device authentication (proving the credential is presented from the authorised device), issuer authentication (proving the credential was issued by a legitimate issuer), and session encryption for secure proximity exchanges. The ARF specifies that the EUDIW must support both mdoc and SD-JWT, with mdoc being particularly suited for offline verification, in-person checks, and scenarios where bandwidth is constrained. For implementers, mdoc requires working with CBOR libraries and understanding the ISO 18013-5 data model, which differs significantly from the JSON-based web ecosystem most developers are familiar with. However, the format's efficiency and its design for real-world presentation scenarios (e.g., showing your ID at a border or a shop) make it indispensable in the EUDIW ecosystem. Organisations that operate in physical verification contexts, such as border control, age verification at point of sale, and law enforcement checks, will particularly need to support mdoc.",
    relatedTerms: ["mdl", "sd-jwt", "arf", "selective-disclosure"],
    category: "Technical Standards",
  },
  {
    slug: "wallet-attestation",
    term: "Wallet Attestation",
    shortDefinition:
      "A cryptographic mechanism that allows a relying party to verify that a wallet application is genuine, certified, and running in a secure environment before accepting credentials from it.",
    fullDefinition:
      "Wallet Attestation is a security mechanism defined in the Architecture Reference Framework that enables relying parties and issuers to verify the authenticity and integrity of a European Digital Identity Wallet instance before engaging in credential exchange. When a wallet presents credentials to a relying party, the relying party needs assurance not only that the credentials themselves are valid, but that the wallet software presenting them is genuine, has not been tampered with, and runs on a device with appropriate security protections. The wallet attestation achieves this by providing a cryptographic proof, issued by the wallet provider (typically the Member State or its delegate), that the specific wallet instance has been certified and meets the security requirements set out in the regulation and implementing acts. The attestation is bound to the wallet's cryptographic keys and to the device's secure element or trusted execution environment, creating a chain of trust from the device hardware through the wallet software to the credentials it holds. Wallet attestation addresses several important security concerns: it prevents the use of cloned or modified wallet applications that might leak user data, it ensures that credentials are only stored and presented by certified software, and it provides a revocation mechanism if a wallet version is found to have a security vulnerability. For relying parties, verifying the wallet attestation is a recommended (and in some cases required) step in the credential verification flow. For organisations implementing relying party systems, this means integrating wallet attestation verification into their technical stack, which involves checking the attestation signature against the wallet provider's published keys and verifying the attestation's validity and revocation status.",
    relatedTerms: ["eudiw", "arf", "conformity-assessment", "relying-party"],
    category: "Technical Standards",
  },
  {
    slug: "psd2",
    term: "PSD2 (Payment Services Directive 2)",
    shortDefinition:
      "The EU directive governing payment services and open banking, which intersects with eIDAS 2.0 through strong customer authentication requirements and the potential use of the EUDIW for payment initiation.",
    fullDefinition:
      "PSD2 (Payment Services Directive 2, Directive (EU) 2015/2366) is the European Union's regulatory framework for payment services, designed to increase competition, innovation, and security in the payments market. PSD2 introduced strong customer authentication (SCA) requirements, mandating that payment service providers verify customer identity using at least two of three factors: knowledge (something the user knows), possession (something the user has), and inherence (something the user is). PSD2 also opened the door to open banking by requiring banks to provide third-party access to customer account data through secure APIs. The intersection between PSD2 and eIDAS 2.0 is significant and growing. The EUDIW, as a government-backed, high-assurance identity instrument, is well positioned to serve as an authentication mechanism that satisfies PSD2's SCA requirements. Several Large-Scale Pilots, notably NOBID, are explicitly testing the use of the wallet for payment-related use cases, including account opening and payment initiation. Under eIDAS 2.0, financial institutions performing customer due diligence under anti-money laundering regulations will be required to accept the EUDIW for identity verification, creating a direct link between the wallet and PSD2-regulated activities. Furthermore, the wallet could streamline know-your-customer (KYC) processes by providing verified Person Identification Data directly from government-issued credentials, reducing the friction and cost of onboarding new banking customers. For financial services organisations, the convergence of PSD2 and eIDAS 2.0 means that wallet integration planning should be part of their broader payments and compliance strategy, not treated as a separate workstream.",
    relatedTerms: ["eidas-2", "eudiw", "relying-party", "amla"],
    category: "Core Regulation",
  },
  {
    slug: "amla",
    term: "Anti-Money Laundering Authority (AMLA)",
    shortDefinition:
      "The new EU authority responsible for overseeing anti-money laundering compliance, whose requirements for customer identity verification intersect directly with eIDAS 2.0 wallet acceptance obligations.",
    fullDefinition:
      "The Anti-Money Laundering Authority (AMLA) is the European Union's new dedicated authority for combating money laundering and terrorist financing, established as part of the EU's comprehensive AML reform package adopted alongside eIDAS 2.0. Headquartered in Frankfurt, AMLA will directly supervise the highest-risk financial entities across the EU and coordinate national supervisory authorities. The connection between AMLA and eIDAS 2.0 is direct and consequential. Under eIDAS 2.0, financial institutions subject to customer due diligence obligations under EU anti-money laundering rules are among the categories of relying parties that must accept the European Digital Identity Wallet for identity verification. This means that the wallet becomes a key instrument in the AML/KYC landscape: when a customer presents their EUDIW with Person Identification Data, the financial institution must accept it as a valid means of verifying their identity. AMLA's supervisory framework will therefore need to account for wallet-based identity verification, including defining standards for how financial institutions verify wallet presentations, handle wallet-based remote onboarding, and maintain records of wallet-based identity checks. The convergence of AML regulation and digital identity creates both opportunities and challenges. On the opportunity side, wallet-based KYC could dramatically reduce the cost and friction of customer onboarding while increasing the reliability of identity data (since PID comes from government-verified sources). On the challenge side, financial institutions must adapt their compliance systems to handle a new identity verification channel and ensure their AML controls remain effective when identity is presented digitally. For compliance officers and regulatory teams, understanding the interaction between AMLA requirements and eIDAS 2.0 wallet obligations is essential for future-proof compliance planning.",
    relatedTerms: ["psd2", "eidas-2", "relying-party", "eudiw"],
    category: "Core Regulation",
  },
  {
    slug: "eid-scheme",
    term: "eID Scheme",
    shortDefinition:
      "A national electronic identification system established by a Member State, defining how electronic identities are issued, managed, and used for authentication.",
    fullDefinition:
      "An eID Scheme is a system for electronic identification established by a Member State under which electronic identification means are issued to natural or legal persons. Under the original eIDAS regulation, eID schemes formed the backbone of cross-border electronic identification: Member States could voluntarily notify their national schemes to the European Commission, after which other Member States were obliged to recognise and accept the notified eID means for cross-border access to public services. However, the voluntary nature of notification and the complexity of the interoperability framework limited adoption. By 2023, fewer than 20 Member States had notified schemes, and cross-border usage remained low. eIDAS 2.0 retains the eID scheme notification mechanism but fundamentally changes the landscape by introducing the European Digital Identity Wallet as a mandatory, standardised alternative. Each Member State must now provide at least one EUDIW, which operates at a high Level of Assurance and serves as a de facto universal eID means. Existing notified eID schemes continue to be valid, but the wallet is expected to become the primary channel for cross-border identification. For Member States, this means updating their national identity infrastructure to support wallet issuance and PID provision while maintaining their existing eID schemes during the transition period. For organisations that currently rely on notified eID schemes through the eIDAS node network, the transition to wallet-based identification requires planning for new protocols (OpenID4VC instead of SAML-based eIDAS nodes), new credential formats, and new user experience flows. Understanding both the legacy eID scheme framework and the new wallet-based approach is essential for a smooth transition.",
    relatedTerms: ["eid", "notified-eid-scheme", "loa", "eudiw"],
    category: "Core Regulation",
  },
  {
    slug: "notified-eid-scheme",
    term: "Notified eID Scheme",
    shortDefinition:
      "An eID scheme that a Member State has formally notified to the European Commission, triggering mandatory cross-border recognition by other Member States for public service access.",
    fullDefinition:
      "A Notified eID Scheme is a national electronic identification scheme that has been formally notified by a Member State to the European Commission under the eIDAS regulation. The notification process involves a peer review by other Member States and the Commission, examining the scheme's compliance with the technical specifications and assurance levels defined in the regulation. Once a scheme is notified, all other Member States are legally obligated to recognise and accept the electronic identification means issued under that scheme for cross-border access to public services at the notified Level of Assurance. The notification specifies the assurance level (low, substantial, or high) at which the scheme operates, and the receiving Member State must accept it for services that require that level or lower. The mutual recognition mechanism is implemented through a network of eIDAS nodes, which are technical gateways that translate between different national eID protocols and formats to enable cross-border authentication. Under eIDAS 2.0, the notified eID scheme framework is supplemented by the EUDIW, which provides a more direct and standardised approach to cross-border identification. However, notified schemes remain valid and relevant during the transition period and beyond. Member States that have invested in robust national eID systems (such as Estonia's ID card, Belgium's itsme, or Italy's SPID) will continue to operate these alongside the wallet. For organisations, particularly those providing public services to cross-border users, understanding notified eID schemes remains important. While the wallet will eventually become the primary cross-border identity channel, the existing eIDAS node infrastructure and notified schemes will coexist for a transition period, and relying parties may need to support both channels during this time.",
    relatedTerms: ["eid-scheme", "eid", "loa", "eidas-2"],
    category: "Governance",
  },
  {
    slug: "supervisory-body",
    term: "Supervisory Body",
    shortDefinition:
      "The national authority designated by each Member State to oversee trust service providers, ensure compliance with eIDAS requirements, and maintain the national Trusted List.",
    fullDefinition:
      "A Supervisory Body is the national authority designated by each EU Member State to oversee and enforce compliance with the eIDAS regulation within its jurisdiction. Under eIDAS 2.0, the supervisory body's role is expanded and strengthened. Its core responsibilities include: supervising Qualified Trust Service Providers (QTSPs) and their services; granting or withdrawing qualified status; maintaining the national Trusted List of qualified trust services and providers; handling incident and breach notifications from trust service providers; conducting or commissioning audits and conformity assessments; and taking enforcement action in case of non-compliance. The supervisory body also plays a role in the wallet ecosystem under eIDAS 2.0. It oversees the registration of relying parties that wish to access wallet data, ensuring that they declare their intended attribute requests and purposes. It also participates in the certification process for wallet solutions and monitors the overall security and trustworthiness of the national digital identity infrastructure. Each Member State must notify the European Commission of its designated supervisory body. Some Member States assign this role to an existing regulatory authority (such as a telecommunications regulator or a data protection authority), while others create a dedicated body. The European Commission publishes a list of all national supervisory bodies, facilitating cross-border cooperation and mutual assistance. For organisations operating as or working with QTSPs, the supervisory body is the primary regulatory point of contact. Understanding the supervisory body's requirements, reporting obligations, and enforcement powers is essential for compliance planning, particularly for organisations seeking to obtain or maintain qualified status for their trust services.",
    relatedTerms: ["qtsp", "trust-list", "conformity-assessment", "trust-framework"],
    category: "Governance",
  },
  {
    slug: "conformity-assessment",
    term: "Conformity Assessment",
    shortDefinition:
      "The formal evaluation process, performed by an accredited body, that verifies whether a trust service provider or wallet implementation meets the regulatory and technical requirements of eIDAS.",
    fullDefinition:
      "Conformity Assessment is the formal evaluation process through which an accredited conformity assessment body (CAB) verifies that a trust service provider, wallet solution, or eID scheme meets the requirements laid down in the eIDAS regulation and its implementing acts. Under eIDAS 2.0, conformity assessment is a critical gateway to qualified status: a trust service provider cannot become a QTSP without first receiving a positive conformity assessment report, and the EUDIW must undergo certification that includes conformity assessment against defined security and functionality criteria. The conformity assessment evaluates multiple dimensions: the provider's security policies and practices; the technical implementation of the service; operational procedures including incident handling and business continuity; the identity verification processes used; and compliance with relevant technical standards (such as ETSI EN 319 401 for trust service provider practices, or Common Criteria for wallet certification). Conformity assessments must be carried out by bodies that are accredited under Regulation (EC) No 765/2008 and have the necessary competence in the relevant area. Under eIDAS 2.0, the conformity assessment requirements are extended to new trust services (such as electronic attestation of attributes and electronic archiving) and to wallet providers. The assessment must be repeated at regular intervals, at least every two years for QTSPs, and whenever there is a significant change to the service. For organisations aspiring to become QTSPs or wallet providers, understanding the conformity assessment process is essential for planning purposes. The assessment can be time-consuming and requires thorough documentation, so early preparation is advisable. For relying parties, the conformity assessment provides assurance that the trust services and wallets they depend on meet a verified standard of quality and security.",
    relatedTerms: ["qtsp", "supervisory-body", "wallet-attestation", "trust-framework"],
    category: "Governance",
  },
  {
    slug: "trust-list",
    term: "Trusted List",
    shortDefinition:
      "An authoritative, machine-readable registry maintained by each Member State listing all qualified trust service providers and their services, forming the backbone of the eIDAS trust model.",
    fullDefinition:
      "A Trusted List is an authoritative, publicly available, machine-readable registry maintained by the supervisory body of each EU Member State that contains information about the trust service providers under its supervision, including their qualified status and the specific qualified trust services they offer. Under eIDAS, the Trusted Lists are the definitive source for determining whether a trust service provider holds qualified status and which of its services are qualified. The European Commission aggregates all national Trusted Lists into a List of Trusted Lists, providing a single entry point for verifiers to check the qualified status of any trust service provider across the EU. Trusted Lists are published in a standardised format (ETSI TS 119 612) that enables automated processing, allowing relying party systems to programmatically verify qualified status during signature validation, seal verification, or credential checking. Under eIDAS 2.0, the role of Trusted Lists is expected to expand to cover new trust services, including electronic attestation of attributes and electronic archiving. The Trusted Lists will also play a role in the wallet ecosystem, as verifiers need to confirm that credential issuers (particularly QTSPs issuing QEAAs) hold valid qualified status. For organisations implementing signature validation, credential verification, or relying party services, integrating with the Trusted Lists is a fundamental requirement. It enables automated, real-time verification of the qualified status of trust services and providers without manual checks. Many existing signature validation solutions already incorporate Trusted List checking, but organisations building new wallet-based verification systems will need to ensure their implementations include this critical trust anchor.",
    relatedTerms: ["qtsp", "supervisory-body", "qeaa", "conformity-assessment"],
    category: "Governance",
  },
  {
    slug: "remote-signing",
    term: "Remote Signing",
    shortDefinition:
      "A cloud-based electronic signing service where the qualified signature creation device is managed by a QTSP, allowing users to create qualified signatures without local hardware.",
    fullDefinition:
      "Remote Signing is a qualified electronic signature service model in which the Qualified Signature Creation Device (QSCD) is hosted and managed in the cloud by a Qualified Trust Service Provider, rather than being physically in the hands of the signatory. This approach eliminates the need for the signatory to carry a smart card, USB token, or other physical device to create Qualified Electronic Signatures. Instead, the signatory authenticates to the remote signing service, typically using multi-factor authentication, and authorises each signature, while the QSCD in the QTSP's secure infrastructure performs the cryptographic signing operation. Remote signing has gained significant momentum in the eIDAS ecosystem and is further boosted by eIDAS 2.0. The regulation mandates that the EUDIW must enable users to create Qualified Electronic Signatures, and remote signing is the primary mechanism by which this will be achieved. The wallet will act as the authentication and authorisation channel: when a user needs to sign a document, the wallet provides the identity assurance (via PID) and the user's consent, while the QTSP's cloud-based QSCD executes the signature. The relevant standard for remote signing is CEN EN 419 241 (Trustworthy Systems Supporting Server Signing), which defines the security requirements for server-based signature creation devices. Under eIDAS 2.0, at least one remote signing service must be offered free of charge to wallet holders for non-professional use, significantly lowering the barrier to qualified signing. For organisations, remote signing simplifies the deployment of QES in business processes. Rather than distributing hardware tokens to all signatories, businesses can integrate with a QTSP's remote signing API and enable qualified signatures through a web or mobile interface, streamlining contract execution, regulatory filings, and any process requiring the highest level of signature assurance.",
    relatedTerms: ["qes", "qtsp", "eudiw", "wallet-attestation"],
    category: "Trust Services",
  },
  {
    slug: "attribute-provider",
    term: "Attribute Provider",
    shortDefinition:
      "An entity that is an authentic source of identity attributes and issues Electronic Attestations of Attributes to wallet holders, such as a university issuing a diploma credential.",
    fullDefinition:
      "An Attribute Provider is an entity that serves as an authentic source of identity attributes and is responsible for issuing Electronic Attestations of Attributes (EAAs) or making its data available for issuance as Qualified Electronic Attestations of Attributes (QEAAs) by a QTSP. Under eIDAS 2.0, the concept of attribute providers is central to the richness and utility of the European Digital Identity Wallet. While the wallet's Person Identification Data is issued by or on behalf of Member States, the wide range of additional credentials that make the wallet genuinely useful, including educational qualifications, professional licences, health records, company registrations, age verification, and more, come from attribute providers. Attribute providers can be public sector bodies (universities, professional regulatory bodies, vehicle registration authorities, health authorities) or private sector entities (employers, banks, insurance companies, certification bodies). Public sector attribute providers are specifically addressed in eIDAS 2.0: Member States must ensure that attributes available in authentic sources maintained by the public sector are made available for issuance as attestations in electronic form, enabling the digitisation of government-issued documents and certificates. The issuance process involves the attribute provider verifying the attributes against its authoritative data and issuing a signed credential in one of the standard formats (SD-JWT or mdoc) to the wallet holder. If the attestation needs to carry qualified status, the attribute provider works with a QTSP to issue a QEAA. For organisations, the attribute provider role represents both an opportunity and an obligation. Organisations that hold authoritative data about individuals or entities should assess whether they need to become attribute providers under eIDAS 2.0 and plan the technical and organisational steps required to issue credentials compatible with the EUDIW ecosystem.",
    relatedTerms: ["eaa", "qeaa", "eudiw", "qtsp"],
    category: "Digital Identity",
  },
];

export function getTermBySlug(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find((term) => term.slug === slug);
}

export function getTermsByCategory(category: string): GlossaryTerm[] {
  return glossaryTerms.filter((term) => term.category === category);
}
